development:
  secret_key_base: 7eb7efef71082d92f710f7736c8cab8d5e42be39d00fec492fa28268ddb4f0e5267e89a8cf3ffb2ff8506ef9a70d24cfe423d1c0abb31572962e20b20e2b7a78
  aws_access_key_id: <%= ENV["MERCARI2_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["MERCARI2_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 7eb7efef71082d92f710f7736c8cab8d5e42be39d00fec492fa28268ddb4f0e5267e89a8cf3ffb2ff8506ef9a70d24cfe423d1c0abb31572962e20b20e2b7a78

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["MERCARI2_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["MERCARI2_SECRET_ACCESS_KEY"] %>
  socket: /var/lib/mysql/mysql.sock
